# -*- coding: utf-8 -*-
"""RAGnarök.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJD4XAeVxNpBvLasgf4yhZdwO2J1Flp_

# **Install Required Libraries**
"""

!pip install -q transformers datasets sentence-transformers faiss-cpu torch accelerate

"""# **Import All Libraries**"""

import torch
import numpy as np
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
import faiss
from transformers import pipeline
from typing import List, Dict, Tuple
import textwrap
import warnings
warnings.filterwarnings('ignore')

"""# **Download and Prepare Dataset**"""

def download_and_chunk_dataset(num_samples=500, chunk_size=100):
    raw_docs = [
        "Artificial intelligence is intelligence demonstrated by machines, in contrast to the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of intelligent agents: any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals. Colloquially, the term artificial intelligence is often used to describe machines that mimic cognitive functions that humans associate with the human mind, such as learning and problem solving.",
        "Machine learning is a subset of artificial intelligence in the field of computer science that often uses statistical techniques to give computers the ability to learn with data, without being explicitly programmed. Machine learning algorithms build a mathematical model based on sample data, known as training data, in order to make predictions or decisions without being explicitly programmed to perform the task.",
        "Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning. Learning can be supervised, semi-supervised or unsupervised. Deep learning architectures such as deep neural networks, deep belief networks, recurrent neural networks and convolutional neural networks have been applied to fields including computer vision, speech recognition, natural language processing, audio recognition, social network filtering, machine translation, bioinformatics, drug design, medical image analysis, material inspection and board game programs.",
        "Natural language processing is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data. The result is a computer capable of understanding the contents of documents, including the contextual nuances of the language within them.",
        "A transformer is a deep learning model that adopts the mechanism of self-attention, differentially weighting the significance of each part of the input data. It is used primarily in the fields of natural language processing and computer vision. Like recurrent neural networks, transformers are designed to process sequential input data, such as natural language, with applications towards tasks such as translation and text summarization.",
        "BERT is a transformer-based machine learning technique for natural language processing pre-training developed by Google. BERT was created and published in 2018 by Jacob Devlin and his colleagues from Google. The original English-language BERT has two models: the BERT BASE model which has 12 layers, 768 hidden, 12 heads, 110M parameters, and the BERT LARGE model which has 24 layers, 1024 hidden, 16 heads, 340M parameters.",
        "GPT is an autoregressive language model that uses deep learning to produce human-like text. It is the third language prediction model in the GPT-n series created by OpenAI. GPT-3's full version has a capacity of 175 billion machine learning parameters. GPT-3 was introduced in May 2020, and was in beta testing as of July 2020. GPT-3 is part of a trend in natural language processing systems of pre-trained language representations.",
        "Retrieval Augmented Generation is an AI framework that combines the strengths of retrieval-based and generation-based models. It retrieves relevant documents from a knowledge base and uses them as context for a language model to generate more accurate and factual responses. RAG helps reduce hallucinations in large language models by grounding their responses in retrieved evidence.",
        "Vector databases are designed to store and query high-dimensional vectors, which are numerical representations of data such as text, images, or audio. They enable similarity search, allowing applications to find items that are semantically similar to a query. Popular vector databases include Pinecone, Weaviate, and Milvus. These databases are essential components of modern RAG systems.",
        "FAISS is a library for efficient similarity search and clustering of dense vectors. It contains algorithms that search in sets of vectors of any size, up to ones that possibly do not fit in RAM. It also includes supporting code for evaluation and parameter tuning. FAISS is written in C++ with complete wrappers for Python. It was developed by Facebook AI Research.",
        "The capital of France is Paris. Paris is the largest city in France and has been its capital since the 10th century. It is one of the most important cultural and economic centers in Europe. The city is famous for landmarks such as the Eiffel Tower, the Louvre Museum, and Notre-Dame Cathedral.",
        "Sir Isaac Newton was an English mathematician, physicist, astronomer, and author who is widely recognized as one of the most influential scientists of all time. He formulated the laws of motion and universal gravitation. Newton discovered gravity when he observed an apple falling from a tree, which led him to formulate his theory of universal gravitation.",
        "The Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is covered with water. Earth's atmosphere consists mostly of nitrogen and oxygen. The planet formed approximately 4.5 billion years ago.",
        "Python is a high-level, interpreted programming language known for its readability and simplicity. It was created by Guido van Rossum and first released in 1991. Python supports multiple programming paradigms, including procedural, object-oriented, and functional programming. It is widely used in data science, machine learning, web development, and automation.",
        "The mitochondria is the powerhouse of the cell. It is a double-membrane-bound organelle found in most eukaryotic organisms. Mitochondria generate most of the cell's supply of adenosine triphosphate (ATP), used as a source of chemical energy. They are also involved in other tasks such as signaling, cellular differentiation, and cell death."
    ]

    raw_docs = raw_docs * (num_samples // len(raw_docs) + 1)
    raw_docs = raw_docs[:num_samples]

    chunks = []
    for doc in raw_docs:
        words = doc.split()
        for i in range(0, len(words), chunk_size):
            chunk = " ".join(words[i:i+chunk_size])
            if len(chunk) > 50:
                chunks.append(chunk)

    print(f"Loaded {len(raw_docs)} documents, Created {len(chunks)} chunks")
    return chunks

chunks = download_and_chunk_dataset(num_samples=300, chunk_size=100)
print(f"\nSample chunk: {chunks[0][:200]}...")

"""# **Load Embedding Model and Create Embeddings**"""

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
chunk_embeddings = embedding_model.encode(chunks, convert_to_numpy=True, show_progress_bar=True)
print(f"Embeddings shape: {chunk_embeddings.shape}")

"""# **Build FAISS Vector Index**"""

dimension = chunk_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(chunk_embeddings)
print(f"FAISS index built with {index.ntotal} vectors")
print(f"Index dimension: {dimension}")

"""# **Retrieval Function**"""

def retrieve(query, top_k=5):
    query_embedding = embedding_model.encode([query], convert_to_numpy=True)
    distances, indices = index.search(query_embedding, top_k)
    results = []
    for idx, dist in zip(indices[0], distances[0]):
        results.append({
            "chunk": chunks[idx],
            "distance": float(dist),
            "index": int(idx)
        })
    return results

test_query = "What is machine learning?"
retrieved = retrieve(test_query, top_k=3)
print(f"Query: {test_query}\n")
for i, doc in enumerate(retrieved):
    print(f"Result {i+1} (distance: {doc['distance']:.4f}):")
    print(f"{doc['chunk'][:150]}...\n")

"""# **Load Generator Model**"""

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    tokenizer="google/flan-t5-base",
    device=0 if torch.cuda.is_available() else -1,
    max_length=200
)
print("Generator model loaded successfully!")

"""# **RAG Generation Function**"""

def rag_generate(query, top_k=5):
    retrieved_docs = retrieve(query, top_k)

    context = "\n".join([f"Passage {i+1}: {doc['chunk']}"
                         for i, doc in enumerate(retrieved_docs)])

    prompt = f"""Based on the following context, answer the question accurately.
If the answer is not in the context, say "I don't have enough information."

Context:
{context}

Question: {query}

Answer:"""

    response = generator(
        prompt,
        max_new_tokens=100,
        do_sample=False,
        temperature=0.1
    )[0]['generated_text']

    answer = response.split("Answer:")[-1].strip()

    return {
        "question": query,
        "answer": answer,
        "retrieved_sources": retrieved_docs
    }

test_result = rag_generate("What is deep learning?", top_k=3)
print(f"Question: {test_result['question']}")
print(f"Answer: {test_result['answer']}")

"""# **Test with Multiple Queries**"""

test_queries = [
    "What is artificial intelligence?",
    "Who discovered gravity?",
    "What is the capital of France?",
    "What is a transformer model?",
    "What is FAISS?"
]

for query in test_queries:
    result = rag_generate(query, top_k=3)
    print(f"\n{'='*70}")
    print(f"❓ Question: {result['question']}")
    print(f"💡 Answer: {result['answer']}")
    print(f"📚 Sources used: {len(result['retrieved_sources'])} chunks")
    print(f"{'='*70}")

"""# **Interactive Query Interface**"""

def ask_question():
    print("\n" + "="*60)
    print("      RAG Question Answering System")
    print("="*60)
    print("Ask any question about the topics in the knowledge base!")
    print("Topics: AI, ML, NLP, Transformers, Vector DBs, Geography, Science")
    print("Type 'quit' to exit")
    print("="*60)

    while True:
        query = input("\n🔍 Enter your question: ").strip()
        if query.lower() == 'quit':
            print("Goodbye!")
            break
        if not query:
            continue

        result = rag_generate(query, top_k=5)

        print(f"\n📝 Answer: {result['answer']}")
        print(f"\n📚 Top Retrieved Sources:")
        for i, src in enumerate(result['retrieved_sources'][:3]):
            print(f"\n--- Source {i+1} (distance: {src['distance']:.4f}) ---")
            print(textwrap.fill(src['chunk'][:300], width=80))

ask_question()

"""# **Evaluation Metrics**"""

def evaluate_retrieval(query, relevant_keywords):
    results = retrieve(query, top_k=10)
    hits = 0
    for res in results:
        for keyword in relevant_keywords:
            if keyword.lower() in res['chunk'].lower():
                hits += 1
                break
    recall = hits / len(relevant_keywords) if relevant_keywords else 0
    return {"query": query, "recall@10": min(recall, 1.0), "hits": hits}

eval_queries = [
    ("Paris capital France", ["Paris", "capital", "France"]),
    ("gravity Newton apple", ["Newton", "gravity", "apple"]),
    ("AI artificial intelligence", ["artificial", "intelligence", "AI"]),
    ("transformer deep learning", ["transformer", "deep learning", "attention"]),
    ("vector database FAISS", ["vector", "FAISS", "database"])
]

print("Retrieval Evaluation Results:")
print("="*60)
for q, keywords in eval_queries:
    score = evaluate_retrieval(q, keywords)
    print(f"Query: {score['query']}")
    print(f"  Recall@10: {score['recall@10']:.2f}")
    print(f"  Hits: {score['hits']}/{len(keywords)}")
    print()

"""# **Compare Different Top-K Values**"""

def compare_topk(query, k_values=[1, 3, 5, 10]):
    print(f"Query: {query}")
    print("="*60)
    for k in k_values:
        result = rag_generate(query, top_k=k)
        print(f"\nTop-K = {k}:")
        print(f"  Answer: {result['answer'][:100]}...")
        print(f"  Avg Distance: {np.mean([s['distance'] for s in result['retrieved_sources']]):.4f}")
    print()

compare_topk("What is machine learning?")
compare_topk("Who is Isaac Newton?")

"""# **Visualize Embedding Similarity**"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

def find_similar_chunks(query, top_k=5):
    results = retrieve(query, top_k=top_k)
    print(f"Query: {query}")
    print("="*60)
    print(f"\n{'Rank':<6} {'Distance':<10} {'Content Preview'}")
    print("-"*60)
    for i, res in enumerate(results):
        preview = res['chunk'][:100].replace('\n', ' ')
        print(f"{i+1:<6} {res['distance']:<10.4f} {preview}...")
    print()
    return results

def visualize_query_results(query, top_k=10):
    results = retrieve(query, top_k=top_k)

    query_embedding = embedding_model.encode([query], convert_to_numpy=True)
    retrieved_embeddings = np.array([chunk_embeddings[res['index']] for res in results])

    all_embeddings = np.vstack([query_embedding, retrieved_embeddings])

    pca = PCA(n_components=2)
    embeddings_2d = pca.fit_transform(all_embeddings)

    plt.figure(figsize=(10, 6))

    plt.scatter(embeddings_2d[1:, 0], embeddings_2d[1:, 1],
                c='steelblue', s=100, alpha=0.6, label='Retrieved Chunks', edgecolors='black')

    plt.scatter(embeddings_2d[0, 0], embeddings_2d[0, 1],
                c='red', s=200, marker='*', label='Query', edgecolors='black', linewidths=2)

    for i, (x, y) in enumerate(embeddings_2d[1:]):
        plt.annotate(f'#{i+1}', (x, y), fontsize=8, ha='center', va='bottom')

    plt.title(f'Query Embedding vs Retrieved Chunks (PCA)\nQuery: "{query[:80]}..."', fontsize=12)
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

def visualize_distance_scores(query, top_k=10):
    results = retrieve(query, top_k=top_k)

    distances = np.array([res['distance'] for res in results])
    labels = [f"Chunk {i+1}" for i in range(len(results))]

    plt.figure(figsize=(10, 5))

    max_dist = distances.max()
    normalized = distances / max_dist if max_dist > 0 else distances
    colors = plt.cm.RdYlGn_r(normalized)
    bars = plt.bar(labels, distances, color=colors, edgecolor='black')

    for bar, dist in zip(bars, distances):
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                f'{dist:.3f}', ha='center', va='bottom', fontsize=9)

    plt.title(f'Similarity Distance Scores (Lower = More Similar)\nQuery: "{query[:80]}..."', fontsize=12)
    plt.xlabel('Retrieved Chunks')
    plt.ylabel('L2 Distance')
    plt.xticks(rotation=45)
    plt.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.show()

def visualize_tsne_clusters(queries_list, top_k=10):
    all_embeddings = []
    all_labels = []

    for i, q in enumerate(queries_list):
        q_emb = embedding_model.encode([q], convert_to_numpy=True)
        results = retrieve(q, top_k=top_k)
        r_embs = np.array([chunk_embeddings[res['index']] for res in results])

        all_embeddings.append(q_emb[0])
        all_labels.append(f'Q{i+1}: {q[:30]}')

        all_embeddings.extend(r_embs)
        all_labels.extend([f'Q{i+1} Results'] * len(r_embs))

    all_embeddings = np.array(all_embeddings)

    tsne = TSNE(n_components=2, random_state=42, perplexity=min(30, len(all_embeddings)-1))
    embeddings_tsne = tsne.fit_transform(all_embeddings)

    plt.figure(figsize=(14, 8))

    unique_labels = list(dict.fromkeys(all_labels))
    colors_list = ['red', 'blue', 'green', 'orange', 'purple', 'brown']

    for label in unique_labels:
        indices = [j for j, l in enumerate(all_labels) if l == label]
        if label.startswith('Q'):
            color_idx = int(label[1]) - 1 if label[1].isdigit() else 0
            plt.scatter(embeddings_tsne[indices, 0], embeddings_tsne[indices, 1],
                       s=200, marker='*', label=label, c=colors_list[color_idx % len(colors_list)],
                       edgecolors='black', linewidths=2)
        else:
            color_idx = int(label[1]) - 1 if label[1].isdigit() else 0
            plt.scatter(embeddings_tsne[indices, 0], embeddings_tsne[indices, 1],
                       s=50, alpha=0.4, label=label, c=colors_list[color_idx % len(colors_list)])

    plt.title('t-SNE Visualization of Query and Retrieved Embeddings', fontsize=14)
    plt.xlabel('t-SNE Component 1')
    plt.ylabel('t-SNE Component 2')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

def visualize_similarity_heatmap(query, top_k=10):
    results = retrieve(query, top_k=top_k)

    retrieved_embeddings = np.array([chunk_embeddings[res['index']] for res in results])
    query_embedding = embedding_model.encode([query], convert_to_numpy=True)
    all_embeddings = np.vstack([query_embedding, retrieved_embeddings])

    similarity_matrix = np.zeros((top_k + 1, top_k + 1))

    for i in range(len(all_embeddings)):
        for j in range(len(all_embeddings)):
            similarity = np.dot(all_embeddings[i], all_embeddings[j]) / (
                np.linalg.norm(all_embeddings[i]) * np.linalg.norm(all_embeddings[j])
            )
            similarity_matrix[i, j] = similarity

    labels = ['Query'] + [f'Chunk {i+1}' for i in range(top_k)]

    plt.figure(figsize=(10, 8))
    sns.heatmap(similarity_matrix, annot=True, fmt='.2f', cmap='coolwarm',
                xticklabels=labels, yticklabels=labels, vmin=-1, vmax=1,
                square=True, cbar_kws={'label': 'Cosine Similarity'})
    plt.title(f'Similarity Heatmap: Query vs Retrieved Chunks\nQuery: "{query[:60]}..."', fontsize=12)
    plt.tight_layout()
    plt.show()

print("="*60)
print("1. Basic Similarity Search Results")
print("="*60)
find_similar_chunks("neural networks and deep learning")
find_similar_chunks("capital city of France")
find_similar_chunks("gravity and physics")

print("\n" + "="*60)
print("2. PCA Visualization: Query vs Retrieved Chunks")
print("="*60)
visualize_query_results("neural networks and deep learning", top_k=10)

print("\n" + "="*60)
print("3. Distance Score Visualization")
print("="*60)
visualize_distance_scores("neural networks and deep learning", top_k=10)

print("\n" + "="*60)
print("4. t-SNE Cluster Visualization for Multiple Queries")
print("="*60)
visualize_tsne_clusters([
    "neural networks and deep learning",
    "capital city of France",
    "gravity and physics"
], top_k=5)

print("\n" + "="*60)
print("5. Similarity Heatmap")
print("="*60)
visualize_similarity_heatmap("machine learning and AI", top_k=8)